/*
 * @Author: Aleksandr Shcherbanyuk
 * @Date: 01/08/2019
 * @Description:
 *		Class TestCoverageObjectTriggerHandler for test coverage and example
 */
public with sharing class TestCoverageObjectTriggerHandler  extends Util_TriggerHandlerImplementation {

	/*
	 *  * * * Example * * *
	 */

	/*
	public override void onBeforeInsertFunction() {
		System.debug('Override onBeforeInsertFunction run');
	}

	public override void onAfterInsertFunction() {
		System.debug('Override onAfterInsertFunction run');
	}

	public override void onBeforeUpdateFunction() {
		System.debug('Override onBeforeUpdateFunction run');
	}

	public override void onAfterUpdateFunction() {
		System.debug('Override onAfterUpdateFunction run');

	}

	public override void execute(QueueableContext context) {
		System.debug(context);
		System.debug(this.getUpdatedRecordsList());
		System.debug(this.getUpdatedRecordsMap());
	}

	*/
}