/*
 * Created by ashcherbanyuk on 7/24/2019.
 */
public virtual class Util_TriggerHandlerImplementation implements Util_ITriggerHandler{


	public virtual void onBeforeInsertFunction() {
		// Just empty implementation
	}

	public virtual void onBeforeUpdateFunction() {
		// Just empty implementation
	}

	public virtual void onBeforeDeleteFunction() {
		// Just empty implementation
	}

	public virtual void onAfterInsertFunction() {
		// Just empty implementation
	}

	public virtual void onAfterUpdateFunction() {
		// Just empty implementation
	}

	public virtual void onAfterDeleteFunction() {
		// Just empty implementation
	}

	public virtual void onAfterUndeleteFunction() {
		// Just empty implementation
	}
}